# Generated by Django 3.0.8 on 2020-07-29 21:09

from django.db import migrations
from django.conf import settings


def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model("sites", "Site")
    Site.objects.all().delete()

    # Register SITE_ID = 1
    DOMAIN_NAME = getattr(settings, "DOMAIN_NAME")
    Site.objects.create(domain=DOMAIN_NAME, name="MetaGrid")


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_sites)]

