# Generated by Django 3.0.8 on 2020-07-29 21:21
from typing import TYPE_CHECKING

from django.conf import settings
from django.db import migrations

if TYPE_CHECKING:
    from allauth.socialaccount.models import SocialApp


def insert_social_apps(apps, schema_editor):
    """Populate the social apps model"""
    SocialAppModel = apps.get_model(
        "socialaccount", "SocialApp"
    )  # type: SocialApp

    # Register SITE_ID = 1
    KEYCLOAK_CLIENT_ID = getattr(settings, "KEYCLOAK_CLIENT_ID")
    keycloak_app = SocialAppModel.objects.create(
        provider="keycloak", name="MetaGrid", client_id=KEYCLOAK_CLIENT_ID
    )

    SiteModel = apps.get_model("sites", "Site")
    sites = SiteModel.objects.all()
    keycloak_app.sites.set(sites)


class Migration(migrations.Migration):

    dependencies = [
        ("mysites", "0001_initial"),
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [migrations.RunPython(insert_social_apps)]
