apiVersion: v1
kind: Service
metadata:
  name: {{ include "metagrid.fullname" . }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
spec:
  type: {{ .Values.react.service.type }}
  ports:
    - port: {{ .Values.react.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metagrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: react
