# Generated by Django 5.0.14 on 2026-07-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("projects", "0002_import_projects_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="project_name",
            field=models.CharField(
                blank=True,
                help_text="Project name for dynamic projects not in the database",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to a project in the database (for static projects)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
