# Generated by Django 5.0.14 on 2026-07-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_search_project_name_alter_search_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="min_created_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Minimum created date filter for STAC searches (ISO datetime format)",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="max_created_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Maximum created date filter for STAC searches (ISO datetime format)",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="is_subscribed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if user has subscribed to change tracking for this search",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="last_checked_time",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                help_text="Unix timestamp (milliseconds) of when user last checked for changes",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="filter_created_since",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                help_text="Temporary filter parameter (ISO datetime string) for viewing filtered subscription results",
            ),
        ),
    ]
