# Generated by Django 3.0.8 on 2020-07-17 20:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_facets_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_auto_20200708_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_facets', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('active_facets', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('text_inputs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=1)),
                ('url', models.URLField(max_length=2000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
                'unique_together': {('user', 'project', 'default_facets', 'active_facets', 'text_inputs')},
            },
        ),
    ]
