# Generated by Django 3.0.8 on 2020-07-20 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='text_inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=1),
        ),
    ]
