# Generated by Django 3.0.8 on 2020-07-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200720_2054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search',
            unique_together=set(),
        ),
    ]
