# Generated by Django 3.1.1 on 2020-11-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_search_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='search',
            name='active_facets',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='search',
            name='default_facets',
            field=models.JSONField(default=dict),
        ),
    ]
