# Generated by Django 3.1.2 on 2020-11-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201102_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='default_facets',
        ),
    ]
