# Generated by Django 3.1.3 on 2020-12-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_search_filename_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='max_version_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='min_version_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
