services:
  django:
    profiles: [ "keycloak" ]
    environment:
      METAGRID_KEYCLOAK_CLIENT_ID: metagrid-localhost
      METAGRID_KEYCLOAK_REALM: metagrid
      METAGRID_KEYCLOAK_URL: http://localhost:1337/auth
      METAGRID_AUTHENTICATION_METHOD: keycloak

  keycloak:
    profiles: [ "keycloak" ]
    image: quay.io/keycloak/keycloak:26.1.2
    depends_on:
      - react
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 1337:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_CLIENT_ID: metagrid-localhost
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
