volumes:
  production_traefik: {}
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  traefik:
    container_name: traefik-prod
    restart: unless-stopped
    build:
      context: traefik
      dockerfile: Dockerfile
    image: metagrid_production_traefik
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:443:443"

  postgres:
    container_name: postgres-prod
    restart: unless-stopped
    build: postgres
    image: metagrid_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/local_postgres_data_backups
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGHOST: postgres
      PGPASSWORD: postgres
      PGUSER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 6

  django:
    container_name: django-prod
    restart: unless-stopped
    build: backend
    image: metagrid_production_django
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    environment:
      PGHOST: postgres
      PGPASSWORD: postgres
      PGUSER: postgres
      DJANGO_DEBUG: False
      DJANGO_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
      DJANGO_SOCIAL_AUTH_REDIRECT_IS_HTTPS: True
      DJANGO_SECURE_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'
      DJANGO_SECURE_SSL_REDIRECT: True
      DJANGO_SESSION_COOKIE_SECURE: True
      DJANGO_CSRF_COOKIE_SECURE: True
      DJANGO_SECURE_HSTS_SECONDS: 518400
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: True
      DJANGO_SECURE_HSTS_PRELOAD: True

  react:
    container_name: react-prod
    restart: unless-stopped
    build:
      context: frontend
      target: prod
    image: metagrid_production_react
    environment:
      - PORT=8080
    depends_on:
      - django
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
