services:
  postgres:
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: ""
      PGPASSWORD: ""
      PGUSER: ""

  django:
    restart: unless-stopped
    environment:
      DOMAIN_NAME: example.com
      DJANGO_SECRET_KEY: ""
      DJANGO_ALLOWED_HOSTS: '["example.com", "localhost"]'
      DJANGO_LOGIN_REDIRECT_URL: https://example.com/search
      DJANGO_LOGOUT_REDIRECT_URL: https://example.com/search
      DJANGO_DEBUG: False
      DJANGO_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
      DJANGO_SOCIAL_AUTH_REDIRECT_IS_HTTPS: True
      DJANGO_SECURE_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'
      DJANGO_SECURE_SSL_REDIRECT: True
      DJANGO_SESSION_COOKIE_SECURE: True
      DJANGO_CSRF_COOKIE_SECURE: True
      DJANGO_SECURE_HSTS_SECONDS: 518400
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: True
      DJANGO_SECURE_HSTS_PRELOAD: True

  react:
    build:
      # The prod build target includes a production ready nginx server
      target: prod
    restart: unless-stopped

  docs:
    restart: unless-stopped
