repositories:
- name: traefik
  url: https://traefik.github.io/charts

releases:
- name: traefik
  chart: traefik/traefik
  version: v34.4.0
- name: metagrid
  chart: ../
  version: "1.6.0"
  values:
    - ingress:
        enabled: true
        tls: false
        additionalAllowedHost: "*"
        className: traefik
  needs:
    - traefik
