{{- if .Values.nodeStatusBackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metagrid.fullname" . }}-node-status-backend
  labels:
    app.kubernetes.io/component: node-status-backend
    {{- include "metagrid.labels" . | nindent 4 }}
  {{- with .Values.nodeStatusBackend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.nodeStatusBackend.serviceAccount.automount }}
{{- end }}
