# Generated by Django 3.0.5 on 2020-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facet',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
