# Generated by Django 3.0.5 on 2020-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200428_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_name',
            field=models.CharField(help_text='The spelled out name of the project.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='The acronym of the project', max_length=255, unique=True),
        ),
    ]
