# Generated by Django 3.0.5 on 2020-04-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_facet_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_variables', to='projects.Facet')),
            ],
            options={
                'verbose_name': 'Facet Variable',
                'verbose_name_plural': 'Facet Variables',
                'unique_together': {('name', 'facet')},
            },
        ),
    ]
