# Generated by Django 3.0.5 on 2020-04-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_facetvariable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacetVariable',
        ),
    ]
