# Generated by Django 3.0.5 on 2020-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_facets_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facets_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
