# Generated by Django 3.0.8 on 2020-07-23 17:13

from django.db import migrations

from metagrid.projects.migrations.scripts.inital_data import (
    insert_data,
    reverse_insert_data,
)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_remove_project_facets_url"),
    ]

    operations = [migrations.RunPython(insert_data, reverse_insert_data)]
