# Generated by Django 3.0.8 on 2020-08-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_auto_20200723_1713"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "FacetGroup",
                "verbose_name_plural": "FacetGroups",
            },
        ),
    ]
