# Generated by Django 3.0.8 on 2020-08-24 20:32

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from metagrid.projects.models import FacetGroup


def insert_groups(apps, schema_editor):
    """Inserts FacetGroup objects into the database."""
    FacetGroupModel = apps.get_model(
        "projects", "FacetGroup"
    )  # type: FacetGroup

    groups = {
        "General": "Least verbose, typically returns many results",
        "Identifiers": "Activities, sources, institutions and experiments",
        "Resolutions": "Simulation resolutions",
        "Labels": "Variants and grids",
        "Classifications": "Variables and realms",
        "CMIP5": "CMIP5 era facets",
        "CMIP6": "CMIP6 era facets",
    }

    for name, description in groups.items():
        FacetGroupModel.objects.get_or_create(
            name=name, description=description
        )


def reverse_insert_groups(apps, schema_editor):
    """Deletes all existing groups."""
    FacetGroupModel = apps.get_model(
        "projects", "FacetGroup"
    )  # type: FacetGroup
    FacetGroupModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_facetgroup"),
    ]

    operations = [migrations.RunPython(insert_groups, reverse_insert_groups)]
