# Generated by Django 3.0.8 on 2020-08-24 20:53

from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from metagrid.projects.models import Facet, FacetGroup


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_auto_20200824_2032"),
    ]

    operations = [
        migrations.AddField(
            model_name="facet",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.FacetGroup",
            ),
        ),
    ]
