# Generated by Django 3.1.1 on 2020-11-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201030_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facet',
            new_name='ProjectFacet',
        ),
    ]
