# Generated by Django 3.1.1 on 2020-11-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20201102_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfacet',
            options={'verbose_name': 'ProjectFacet', 'verbose_name_plural': 'ProjectFacets'},
        ),
    ]
