# Generated by Django 3.1.1 on 2020-11-02 19:15
from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from metagrid.projects.models import Facet, ProjectFacet


def insert_facets(apps, schema_editor):
    """Inserts Facet objects using the existing ProjectFacet objects
    """
    ProjectFacetModel = apps.get_model(  # type: ProjectFacet
        "projects", "ProjectFacet"
    )

    facet_names = (
        ProjectFacetModel.objects.values_list("name", flat=True)
        .order_by("name")
        .distinct()
    )

    FacetModel = apps.get_model(  # type: Facet
        "projects", "Facet"
    )
    for name in facet_names:
        FacetModel.objects.create(name=name)


def reverse_insert_facets(apps, schema_editor):
    FacetModel = apps.get_model(  # type: Facet
        "projects", "Facet"
    )

    FacetModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_auto_20201102_1913"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Facet",
                "verbose_name_plural": "Facets",
            },
        ),
        migrations.RunPython(insert_facets, reverse_insert_facets),
    ]
