# Generated by Django 3.1.1 on 2020-11-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_facet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfacet',
            name='facet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.facet'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfacet',
            unique_together={('facet', 'name', 'project')},
        ),
    ]
