# Generated by Django 3.1.1 on 2020-11-02 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20201102_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfacet',
            name='facet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.facet'),
        ),
        migrations.AlterField(
            model_name='projectfacet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.facetgroup'),
        ),
        migrations.AlterField(
            model_name='projectfacet',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectfacet',
            unique_together={('project', 'facet')},
        ),
    ]
