# Generated by Django 3.1.1 on 2020-11-02 22:30
# Generated by Django 3.1.1 on 2020-11-02 22:22
from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from metagrid.projects.models import Facet, ProjectFacet


def nullify_name_field(apps, schema_editor):
    ProjectFacetModel = apps.get_model(
        "projects", "ProjectFacet"
    )  # type: ProjectFacet

    ProjectFacetModel.objects.all().update(name=None)


def reverse_nullify_name_field(apps, schema_editor):
    FacetModel = apps.get_model("projects", "Facet")  # type: Facet
    ProjectFacetModel = apps.get_model(
        "projects", "ProjectFacet"
    )  # type: ProjectFacet

    project_facets = ProjectFacetModel.objects.all()
    for project_facet in project_facets:
        project_facet.name = project_facet.facet.name

    ProjectFacetModel.objects.bulk_update(project_facets, ["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_auto_20201102_2230"),
    ]

    operations = [
        migrations.RunPython(nullify_name_field, reverse_nullify_name_field)
    ]
