# Generated by Django 3.1.12 on 2021-07-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_projectfacet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(help_text='The url associated with this project.', max_length=510, null=True, unique=True),
        ),
    ]
