# Generated by Django 3.2.13 on 2022-05-05 16:59

from typing import TYPE_CHECKING

from django.db import migrations

import logging

logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from metagrid.projects.models import Project

# Facets are pulled from ESGF Search API JSON results
PROJECT_LINKS = {
    "CMIP6": "https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6/",
    "CMIP5": "https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip5/",
    "E3SM": "https://e3sm.org/",
    "CMIP3": "https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip3/",
    "input4MIPs": "https://esgf-node.llnl.gov/projects/input4mips/",
    "obs4MIPs": "https://esgf-node.llnl.gov/projects/obs4mips/",
}


def insert_link_data(apps, schema_editor):
    # We can't import the Project and Facet models directly as it may be
    # a newer version than this migration expects. We use the historical
    # version.
    ProjectModel = apps.get_model("projects", "Project")  # type: Project
    logger.info("Test")
    for project in ProjectModel.objects.all():

        project.project_url = PROJECT_LINKS.get(project.name)
        project.save()


def reverse_insert_data(apps, schema_editor):
    ProjectModel = apps.get_model("projects", "Project")  # type: Project

    ProjectModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_auto_20210819_2215"),
    ]

    operations = [migrations.RunPython(insert_link_data, reverse_insert_data)]
