apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metagrid.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "metagrid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ list (include (print $.Template.BasePath "/backend/secret.yaml") .) (include (print $.Template.BasePath "/backend/configmap.yaml") .) | join "_" | sha256sum }}
      {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: backend
        {{- include "metagrid.labels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metagrid.fullname" . }}-backend
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
      - name: backend
        securityContext:
          {{- toYaml .Values.backend.securityContext | nindent 12 }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "metagrid.fullname" . }}
        - configMapRef:
            name: {{ include "metagrid.fullname" . }}
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DJANGO_ALLOWED_HOSTS
          {{- $hosts := list "localhost" "$(THIS_POD_IP)" }}
          {{- range .Values.ingress.hosts }}
            {{- $hosts = append $hosts . }}
          {{- end }}
          value: {{ toJson $hosts | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.port }}
          protocol: TCP
        {{- if .Values.backend.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.backend.startupProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.backend.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.startupProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}
          successThreshold: {{ .Values.backend.startupProbe.successThreshold }}
        {{- end }}
        {{- if .Values.backend.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.backend.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
        {{- with .Values.backend.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.backend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
