{{- if .Values.backend.migrateJob.enabled -}}
{{- with .Values.backend.projects }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" $ }}-projects
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: migrate-job
    {{- include "metagrid.labels" . | nindent 4 }}
data:
  initial_projects_data.py: |
  {{ $.Values.backend.projects | nindent 4 }}
---
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "metagrid.fullname" $ }}-django-migrate
  labels:
    app.kubernetes.io/component: migrate-job
    {{- include "metagrid.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.backend.migrateJob.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metagrid.fullname" . }}-backend
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
      - name: migrations
        securityContext:
          {{- toYaml .Values.backend.securityContext | nindent 12 }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "metagrid.fullname" . }}-config
        command: ['/bin/bash', '-c']
        args:
        - python manage.py migrate
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
        volumeMounts:
        {{- with .Values.backend.projects}}
        - name: projects
          mountPath: /app/metagrid/initial_projects_data.py
          subPath: initial_projects_data.py
        {{- end }}
        {{- with .Values.backend.volumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
      - name: projects
        configMap:
          name: {{ include "metagrid.fullname" . }}-projects
      {{- with .Values.backend.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
