apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}-config
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
stringData:
  PGHOST: {{ include "postgresql-ha.pgpool" .Subcharts.postgresql }}
  PGUSER: {{ include "postgresql-ha.postgresqlUsername" .Subcharts.postgresql }}
  PGPASSWORD: {{ coalesce .Subcharts.postgresql.Values.postgresql.password .Subcharts.postgresql.Values.global.postgresql.password }}
  {{- tpl (toYaml .Values.config) . | nindent 2 }}
