apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}-config
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
stringData:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ include "metagrid.postgresql_uri" . }}
  {{- else }}
  DATABASE_URL: {{ required "Setting config.DATABASE_URL is required when using a self managed PostgreSQL database" .Values.config.DATABASE_URL }}
  {{- end }}
  {{- if .Values.features.nodeStatus.enabled }}
  {{ $defaultNodeStatusUrl := printf "http://%s-node-status-backend:9090/api/v1/query?query=probe_success%7Bjob%3D%22http_2xx%22%2C+target%3D~%22.%2Athredds.%2A%22%7D" (include "metagrid.fullname" .) }}
  METAGRID_STATUS_URL: {{ default $defaultNodeStatusUrl .Values.features.nodeStatus.url }}
  {{- end }}
  {{- tpl (toYaml .Values.config) . | nindent 2 }}
  {{- if .Values.features.wget.enabled }}
  DATA_UPLOAD_MAX_NUMBER_FIELDS: {{ .Values.features.wget.uploadMaxFields | quote }}
  GLOBUS_PUBLIX_INDEX_ENDPOINT_ID: {{ .Values.features.wget.globusPublixIndex | quote }}
  WGET_SCRIPT_FILE_DEFAULT_LIMIT: {{ .Values.features.wget.limit.default | quote }}
  WGET_SCRIPT_FILE_MAX_LIMIT: {{ .Values.features.wget.limit.max | quote }}
  WGET_MAX_DIR_LENGTH: {{ .Values.features.wget.maxDirLength | quote }}
  {{- end }}
