apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}-config
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
stringData:
  {{- tpl (toYaml .Values.config) . | nindent 2}}
