apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}-config
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
stringData:
  PGHOST: {{ include "postgresql-ha.pgpool" .Subcharts.postgresql }}
  PGUSER: {{ include "postgresql-ha.postgresqlUsername" .Subcharts.postgresql }}
  PGPASSWORD: {{ coalesce .Subcharts.postgresql.Values.postgresql.password .Subcharts.postgresql.Values.global.postgresql.password }}
  {{- if .Values.features.nodeStatus.enabled }}
  {{ $defaultNodeStatusUrl := printf "http://%s-node-status-backend:9090/api/v1/query?query=probe_success%7Bjob%3D%22http_2xx%22%2C+target%3D~%22.%2Athredds.%2A%22%7D" (include "metagrid.fullname" .) }}
  METAGRID_STATUS_URL: {{ default $defaultNodeStatusUrl .Values.features.nodeStatus.url }}
  {{- end }}
  {{- tpl (toYaml .Values.config) . | nindent 2 }}
