apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
stringData:
  {{- if not .Values.wget.url }}
  {{- if and (or .Values.wget.globusClientID .Values.auth.globus.key) (or .Values.wget.globusClientSecret .Values.auth.globus
  .secret) }}
  GLOBUS_CLI_CLIENT_ID: {{ .Values.wget.globusClientID | default .Values.auth.globus.key }}
  GLOBUS_CLI_CLIENT_SECRET: {{ .Values.wget.globusClientSecret | default .Values.auth.globus.secret }}
  {{- else }}
  {{- fail "Either wget.globusClientID/wget.globusClientSecret or auth.globus.key/auth.globus.secret must be defined when wget.url is not set" }}
  {{- end }}
  {{- end }}
  {{- if .Values.auth.enabled }}
  METAGRID_AUTHENTICATION_METHOD: {{ .Values.auth.type }}
  {{- if eq .Values.auth.type "globus" }}
  METAGRID_SOCIAL_AUTH_GLOBUS_KEY: {{ .Values.auth.globus.key }}
  METAGRID_SOCIAL_AUTH_GLOBUS_SECRET: {{ .Values.auth.globus.secret }}
  {{- else if eq .Values.auth.type "keycloak" }}
  METAGRID_KEYCLOAK_URL: {{ .Values.auth.keycloak.url }}
  METAGRID_KEYCLOAK_REALM: {{ .Values.auth.keycloak.realm }}
  METAGRID_KEYCLOAK_CLIENT_ID: {{ .Values.auth.keycloak.clientId }}
  {{- end }}
  {{- end }}
  {{- if and .Values.hotjar.id .Values.hotjar.sv }}
  METAGRID_HOTJAR_ID: {{ .Values.hotjar.id }}
  METAGRID_HOTJAR_SV: {{ .Values.hotjar.sv }}
  {{- end }}
  {{- if .Values.googleAnalyticsTrackingId }}
  METAGRID_GOOGLE_ANALYTICS_TRACKING_ID: {{ .Values.googleAnalyticsTrackingId }}
  {{- end }}
  DJANGO_SECRET_KEY: {{ default (randBytes 32) .Values.django.secretKey }}
  {{- if .Values.django.adminUrl }}
  METAGRID_ADMIN_URL: {{ .Values.django.adminUrl }}
  {{- end }}
  {{- if .Values.django.admins }}
  METAGRID_ADMINS: {{ toJson .Values.django.admins | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ include "metagrid.postgresql_uri" . }}
  {{- else }}
  DATABASE_URL: {{ required "Setting `django.databaseUri` is required when using a self managed PostgreSQL database" .Values.django.databaseUri }}
  {{- end }}
  {{- range $key, $value := .Values.django.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

