apiVersion: v1
kind: Service
metadata:
  name: {{ include "metagrid.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "metagrid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "metagrid.selectorLabels" . | nindent 4 }}
