# Generated by Django 3.1.3 on 2021-02-02 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('period', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('BW', 'Bi-weekly'), ('M', 'Monthly')], default='W', max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('facets', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SavedSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptions', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SavedSubscriptions',
                'verbose_name_plural': 'SavedSubscriptions',
            },
        ),
    ]
