# Generated by Django 3.1.6 on 2021-02-10 18:41

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from metagrid.subscriptions.models import SavedSubscriptions
    from metagrid.users.models import User


def assign_subscription_records(apps, schema_editor):
    UserModel = apps.get_model("users", "User")  # type: User
    SavedSubscriptionsModel = apps.get_model(
        "subscriptions", "SavedSubscriptions"
    )  # type: SavedSubscriptions

    users = UserModel.objects.all()

    for user in users:
        if SavedSubscriptionsModel.objects.filter(user=user).exists() is False:
            SavedSubscriptionsModel(user=user).save()


def reverse_assign_subscription_records(apps, schema_editor):
    SavedSubscriptionsModel = apps.get_model(
        "subscriptions", "SavedSubscriptions"
    )  # ty»pe: SavedSubscriptions
    SavedSubscriptionsModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            assign_subscription_records, reverse_assign_subscription_records
        )
    ]
