# Generated by Django 3.1.3 on 2021-02-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210210_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
