# Generated by Django 3.1.3 on 2021-02-12 03:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_delete_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedSubscriptions',
            new_name='Subscriptions',
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Subscriptions', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
