{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}-postgresql-config
  labels:
    app.kubernetes.io/component: database
    {{- include "metagrid.labels" . | nindent 4 }}
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
  POSTGRES_DB: {{ .Values.postgresql.database }}
{{- end }}
