# Generated by Django 3.0.7 on 2020-06-26 21:06

from django.db import migrations

import metagrid.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200624_1918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', metagrid.users.models.UserManager()),
            ],
        ),
    ]
