volumes:
  production_traefik: {}
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  traefik:
    restart: unless-stopped
    build:
      context: ./traefik
      dockerfile: Dockerfile
      args:
        host_name: example.com
        frontend_prefix: ""
        backend_prefix: frontend-config.js
    image: metagrid_production_traefik
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:443:443"
  postgres:
    restart: unless-stopped
    build: postgres
    image: metagrid_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/local_postgres_data_backups
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGHOST: localhost
      PGPASSWORD: postgres
      PGUSER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 6

  django:
    restart: unless-stopped
    build: backend
    image: metagrid_local_django
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      PGHOST: localhost
      PGPASSWORD: postgres
      PGUSER: postgres
      DOMAIN_NAME: example.com
      DOMAIN_SUBDIRECTORY: ""
      DJANGO_ALLOWED_HOSTS: '["example.com", "localhost"]'
      DJANGO_DEBUG: False
      DJANGO_SECRET_KEY: ""
      DJANGO_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
      DJANGO_SOCIAL_AUTH_REDIRECT_IS_HTTPS: True
      DJANGO_SECURE_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'
      DJANGO_SECURE_SSL_REDIRECT: True
      DJANGO_SESSION_COOKIE_SECURE: True
      DJANGO_CSRF_COOKIE_SECURE: True
      DJANGO_SECURE_HSTS_SECONDS: 518400
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: True
      DJANGO_SECURE_HSTS_PRELOAD: True
      METAGRID_SEARCH_URL: https://esgf-node.llnl.gov/esg-search/search
      METAGRID_WGET_URL: https://esgf-node.llnl.gov/esg-search/wget
      METAGRID_STATUS_URL: https://nimbus-dev.llnl.gov/metagrid-backend/proxy/status
      METAGRID_SOLR_URL: https://esgf-node.llnl.gov/esg-search
      METAGRID_SOCIAL_AUTH_GLOBUS_KEY: ""
      METAGRID_SOCIAL_AUTH_GLOBUS_SECRET: ""
      METAGRID_GLOBUS_CLIENT_ID: ""
      METAGRID_AUTHENTICATION_METHOD: globus
      METAGRID_FOOTER_TEXT: |
        Privacy & Legal Notice: [https://www.llnl.gov/disclaimer.html](https://www.llnl.gov/disclaimer.html)    
        Learn about the Department of Energy's Vulnerability Disclosure Program (VDP): 
        [https://doe.responsibledisclosure.com/hc/en-us](https://doe.responsibledisclosure.com/hc/en-us)
    ports:
      - 5000:5000

  react:
    restart: unless-stopped
    build:
      context: frontend
      target: prod
    image: metagrid_local_react
    environment:
      - PORT=8080
    depends_on:
      - django
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

