# Default values for metagrid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

django:

  replicaCount: 1

  image:
    repository: image-registry.openshift-image-registry.svc:5000/cli137/django
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  migrateJob:
    enabled: true

  env:
    CORS_ORIGIN_WHITELIST: ""
    DJANGO_ADMIN_URL: ""
    DJANGO_ALLOWED_HOSTS: ""
    DJANGO_SECRET_KEY: ""
    DJANGO_SECURE_SSL_REDIRECT: "False"
    DJANGO_SETTINGS_MODULE: config.settings.production
    DOMAIN_NAME: ""
    DOMAIN_SUBDIRECTORY: ""
    KEYCLOAK_CLIENT_ID: ""
    KEYCLOAK_REALM: ""
    KEYCLOAK_URL: '{{ include "metagrid.keycloak_url" $ }}'
    DATABASE_URL: '{{ include "metagrid.pg_uri" $ }}'
    # POSTGRES_HOST: '{{ include "metagrid.pg_host" $ }}'
    # POSTGRES_PORT: '{{ include "metagrid.pg_port" $ }}'
    # POSTGRES_DB: '{{ include "metagrid.pg_db" $ }}'
    # POSTGRES_USER: '{{ include "metagrid.pg_user" $ }}'
    # POSTGRES_PASSWORD: '{{ include "metagrid.pg_pass" $ }}'

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

react:

  replicaCount: 1

  image:
    repository: image-registry.openshift-image-registry.svc:5000/cli137/react
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  env:
    REACT_APP_METAGRID_API_URL: http://{{ (index .Values.react.ingress.hosts 0).host }}
    REACT_APP_WGET_API_URL: https://greyworm1-rh7.llnl.gov/wget
    REACT_APP_ESGF_NODE_URL: esg-search/search
    REACT_APP_ESGF_NODE_STATUS_URL: https://aims4.llnl.gov/prometheus/api/v1/query?query=probe_success%7Bjob%3D%22http_2xx%22%2C+target%3D~%22.%2Athredds.%2A%22%7D
    REACT_APP_KEYCLOAK_REALM: esgf
    REACT_APP_KEYCLOAK_URL: https://keycloak.metagrid.com/auth
    REACT_APP_KEYCLOAK_CLIENT_ID: frontend
    GENERATE_SOURCEMAP: 'false'

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: esgf.apps.marble.ccs.ornl.gov
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

postgresql:
  enabled: true

extraManifests: {}