#!/bin/sh

[ -n "${DEBUG}" ] && set -x

export RELEASE="${RELEASE:-production}"
export ENV_FILE="${ENV_FILE:-/env}"
export HTML_PATH="${HTML_PATH:-/usr/share/nginx/html}"
export STATIC_PATH=""
export STATIC_URL="${PUBLIC_URL}${STATIC_PATH}"
export RUNTIME_PATH="${HTML_PATH}${STATIC_PATH}/runtime_env.js"

TMP_PATH=/tmp

if [ ! -e "$(dirname ${RUNTIME_PATH})" ]
then
    mkdir -p "$(dirname ${RUNTIME_PATH})"
fi

if [ "${RELEASE}" = "production" ]
then
    export STATIC_PATH="/static/js"
fi

if [ -e "${ENV_FILE}" ]; then
    echo "window.ENV = {" > "${RUNTIME_PATH}"

    while read -r line; do
        [ -z "$(echo ${line} | grep -vE '^# |^$')" ] && continue

        varname=$(printf '%s\n' "${line}" | cut -d"=" -f1)
        varvalue=$(printenv "${varname}")

        if [ -z "${varvalue}" ]; then
            varvalue=$(printf '%s\n' "${line}" | cut -d"=" -f2)

            export "${varname}"="${varvalue}"
        fi

        echo "  ${varname}: \"${varvalue}\"," >> "${RUNTIME_PATH}"
    done < ${ENV_FILE}

    echo "};" >> "${RUNTIME_PATH}"
fi

if [ ! -e "/index.html" ]; then
    cp "${HTML_PATH}/index.html" "${TMP_PATH}/index.html"
fi

if [ "${RELEASE}" = "production" ]
then
    if [ -z "${PUBLIC_URL}" ]
    then
        envsubst '${PREVIOUS_URL}' < /nginx.conf > /etc/nginx/conf.d/default.conf
        export PUBLIC_URL=""
    else
        envsubst '${PREVIOUS_URL},${PUBLIC_URL}' < /nginx.subdir.conf > /etc/nginx/conf.d/default.conf

        # Fixes react-scripts static path e.g. /static/ -> $PUBLIC_URL/static/
        sed -i"" "s/\"\/static\//\"\$PUBLIC_URL\/static\//g" "${TMP_PATH}/index.html"
    fi

fi

envsubst '$STATIC_URL,$PUBLIC_URL,$REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID' < "${TMP_PATH}/index.html" > "${HTML_PATH}/index.html"

exec "$@"
