name: Helm chart

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: Metagrid
        repository: esgf2-us
        tag: ${{ github.ref_name }}
        path: helm
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'