name: Pre-commit Checks
on:
  push:
    branches: [master]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Required to run the local ESLint hook
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: |
          cd frontend
          pnpm install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          pip3 install --upgrade pip
          pip3 install setuptools --upgrade
          pip3 install --no-cache-dir -r backend/requirements/local.txt

      - name: Run pre-commit
        run: pre-commit run --all-files
